config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  resources :orders

  # resources :line_items
  # resource :carts, only:[:show]
  resources :brands
  resources :types
  devise_for :users
  resources :products
  get 'home/index'
  get 'home/faq'
  get 'home/help'
  get 'home/about'
  get 'home/dashboard'
  root 'home#index'

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  post 'orders/:id/confirm' => "orders#toggle_confirm", as: "toggle_confirm"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/home.rb
class Home < ApplicationRecord
    has_one_attached :image_product
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @cart = @current_cart
    
  end
 
  def about
  end
  def dashboard
    @products = Product.filter_search(params[:name_search], params[:type_select], params[:brand_select])
  end

  # def cart
  #   quantity = params[:quantity].to_i
  #   product_id = params[:product]
  #   @product = Product.find(product_id)
  #   @cart.add(@product, @product.price_product, quantity)
  #   redirect_to  request.referer || "/"
  #   flash[:notice] = "#{@product.name} has been added to the Cart."
  # end

  # def create_order
  #   total_price_delivery = 0
  #   total_price_items = @cart.total_items
  #   total_all_price = total_price_delivery + total_price_items
  
  #   @order = Order.new
  #   @order.number = "#{current_user.id}-#{Time.now.to_i}"
  #   @order.user_id = current_user.id
  #   @order.total_price_items = total_price_items
  #   @order.total_price_delivery = total_price_delivery
  #   @order.total_all_price = total_all_price
  #   @order.save
  #   @cart.update(:order_id => @order.id)
  #   redirect_to root_path
  #   flash[:notice] = "Your Order has been created"
  # end
  




  def cover_url 
    rails_blob_path(self.image_product, disposition: "attachment", only_path: true)
  end

  def persisted?
    false
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">Tentang Kami</span></h2>
        <p class="deskripsi"></p>Anggota Kelompok Kami
            <div class="container-fluid pt-5">
    <div class="row px-xl-5 pb-3">
    <!-- Optional JavaScript; choose one of the two! -->
    <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
        <div class="product-item  border-light-0 mb-4">
            <div class=" product-img position-relative p-0">
                <%= image_tag "3221600043_M Thoyyib Asshiddiqy.jpg", width:"200", height:"200"%>
                <div class="card-body text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">M. Thoyyib Asshiddiqy</h6>
                    <div class="d-flex justify-content-center">
                        <h6>3221600043</h6> 
                    </div>
                </div>
            </div>
            <div class="p-0"  >
               
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
        <div class="product-item  border-light-0 mb-4">
            <div class=" product-img position-relative p-0">
                <%= image_tag "3221600054_Muhammad Faishal Maulana Insani.jpg", width:"200", height:"200"%>
                <div class="card-body text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">Muhammad Faishal Maulana Insani</h6>
                    <div class="d-flex justify-content-center">
                        <h6>3221600054</h6>
                    </div>
                </div>
            </div>
            <div class="p-0"  >
               
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
        <div class="product-item  border-light-0 mb-4">
            <div class=" product-img position-relative p-0">
                <%= image_tag "3221600059_Ulfa Dwi Yanti.jpg", width:"200", height:"200"%>
                <div class="card-body text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">Ulfa Dwi Yanti</h6>
                    <div class="d-flex justify-content-center">
                        <h6>3221600059</h6>
                    </div>
                </div>
            </div>
            <div class="p-0"  >
               
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
        <div class="product-item  border-light-0 mb-4">
            <div class=" product-img position-relative p-0">
                <%= image_tag "3221600060_Mohamad Rizky Setiawan.jpg", width:"200", height:"200"%>
                <div class="card-body text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">Mohamad Rizky Setiawan</h6>
                    <div class="d-flex justify-content-center">
                        <h6>3221600060</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/cart.html.erb
<section class="vh-200" style="background-color: #508bfc;">
  <section class="h-100 gradient-custom">
    <div class="container py-5">
      <div class="row d-flex justify-content-center my-4">
        <div class="col-md-8">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Keranjang</h5>
            </div>
            <!-- ISI PRODUK -->
            <div class="card-body">

            </div>
          </div>
          <div class="mb-0">    
          </div>
        </div>
      
            <!-- Tabel -->
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Total</h5>
            </div>
            <div class="card-body">
              <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                 Produk
                 <span>Rp. 12.500.000</span>
               </li>
                <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                  Pengiriman
                  <span>Gratis</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                  <div>
                    <strong>Total Pembayaran</strong>
                  </div>
                  <span><strong>Rp. 12.500.000</strong></span>
                </li>
              </ul>
              <button type="button" class="btn btn-primary btn-lg btn-block">Bayar</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</section>

app/views/home/dashboard.html.erb
<div class="container">
  <!-- Jika Admin -->
  <% if current_user.try(:admin?) %>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <%= link_to "Tipe", types_path, class:"btn btn-info" %>
    <%= link_to "Merek", brands_path, class:"btn btn-dark" %>
    <%= link_to "Order", orders_path, class:"btn btn-dark" %>
    
  </div>
  <%= render "products/search" %>

  <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th>Nama Produk</th>
        <th>Tipe Produk</th>
        <th>Merek Produk</th>
        <th>Kuantitas</th>
        <th>Harga</th>
        <th> </th>
        <th> </th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <div id="products">
        <% @products.each do |product| %>
          <%= render product %>
        <% end %>
      </div>
    </tbody>
  </table>
  <%= link_to "Produk Baru", new_product_path, class:"btn btn-secondary" %>
</div>
<!-- Jika bukan admin -->
<% else %>
Access Denied
<%end%>

app/views/home/index.html.erb
<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">Kategori</span></h2>
        <div class="container-fluid pt-5">
            <div class="row px-xl-5 pb-3">
                <!-- Categories Start -->
                <div class="col-lg-4 col-md-6 pb-1">
                    <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                        <p class="text-right">Rekomendasi</p>
                        <a href="/products?name_search=&type_select=1&brand_select=&commit=search" class="cat-img position-relative overflow-hidden mb-3"> <%= image_tag "logo.png", class:"img-fluid" %> </a>
                        <h5 class="font-weight-semi-bold m-0">Android</h5>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 pb-1">
                    <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                        <p class="text-right">Rekomendasi</p>
                        <a href="products?name_search=&type_select=2&brand_select=&commit=search" class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" src="images/logo.png" alt=""> <%= image_tag "logo.png", class:"img-fluid" %> </a>
                        <h5 class="font-weight-semi-bold m-0">Laptop</h5>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 pb-1">
                    <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                        <p class="text-right">Rekomendasi</p>
                        <a href="" class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" src="images/logo.png" alt="">  <%= image_tag "logo.png", class:"img-fluid" %> </a>
                        <h5 class="font-weight-semi-bold m-0">IOS</h5>
                    </div>
                </div>
                <!-- Categories End -->

                <!-- Products Start -->
                <div class="container-fluid pt-5">
                    <div class="text-center mb-4">
                        <h2 class="section-title px-5"><%= link_to "Produk yang Populer", products_path, class:"px-2" %></h2>
                    </div>
                    <div class="container-fluid pt-5">
                        <div class="row px-xl-5 pb-3">
                            <% @products.each do |product| %>
                            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                                <div class="card product-item border-0 mb-4">
                                    <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                                        <% if product.image_product.attached?%>
                                            <img src="<%= (url_for(product.image_product))%>" class="img-fluid w-100" alt="">
                                        <%else%>
                                            <%= image_tag "logo.png", class:"img-fluid w-100" %>
                                        <%end%>
                                    </div>
                                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                                        <h6 class="text-truncate mb-3"><%= product.name %></h6>
                                        <div class="d-flex justify-content-center">
                                        <h6><%= product.price %></h6>
                                    </div>
                                </div>
                                <div class="card-footer d-flex justify-content-between bg-light border">
                                    <%= link_to "Lihat Selengkapnya", product, class:"btn btn-outline-info" %></td>
                                    <div class="action">
                                    <%= button_to "Tambahkan ke Keranjang", line_items_path(:product_id => product.id), class:"btn btn-outline-info"%>
                                    </div>

                                </div>
                            </div>
                        </div>
                            <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>