config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  resources :orders

  # resources :line_items
  # resource :carts, only:[:show]
  resources :brands
  resources :types
  devise_for :users
  resources :products
  get 'home/index'
  get 'home/faq'
  get 'home/help'
  get 'home/about'
  get 'home/dashboard'
  root 'home#index'

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  post 'orders/:id/confirm' => "orders#toggle_confirm", as: "toggle_confirm"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
  # belongs_to :user
  has_many :order_items, dependent: :destroy
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def toggle_confirm
    @order = Order.find(params[:id])  
    @order.toggle!(:confirmed)  
    redirect_to orders_url 
  end

  def create
    @order = Order.create(order_params)
    # @order.add_line_items_from_cart(@cart)
    # @current_cart.line_items.each do |item|
    #   item.cart_id = nil
    #   @order.line_items << item
    # end

    # @order.save
    # Cart.destroy(session[:cart_id])
    # session[:cart_id] = nil
    # @order.save
    if @order.save # this will save the order 
       
      @current_cart.line_items.each do |line_item|
         # using the bang (!) to save to the DB and raise any errors
         # rather than failing silently
         @order.order_items.create!(         
            product_id: line_item.product_id,
            quantity:   line_item.quantity 
         )
         line_item.cart_id = nil
      end
      
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil

       redirect_to @order, notice: 'Order was successfully created.'
    else
       redirect_to root_path, notice: 'Something went wrong saving the order.'
    end 

    # respond_to do |format|
    #   if @order.save
    #     format.html { redirect_to @order, notice: 'Order was successfully created.' }
    #     format.json { render :show, status: :created, location: @order }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @order.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully Done.' }
      format.json { head :no_content }
    end
  end


  
  private
  def order_params
    params.require(:order).permit(:name, :email, :address, :pay_method)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div class="container">
  <!-- Jika Admin -->
  <% if current_user.try(:admin?) %>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <%= link_to "Tipe", types_path, class:"btn btn-info" %>
    <%= link_to "Merek", brands_path, class:"btn btn-dark" %>
    <%= link_to "Dashboard", home_dashboard_path, class:"btn btn-dark" %>
    
  </div>

  <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th>Nama User</th>
        <th>Email</th>
        <th>Alamat</th>
        <th>Produk</th>
        <th></th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <div id="products">
        <% @orders.each do |order| %>
          <div>
            <tr>
              <td><%= order.name %></td>
              <td><%= order.email %></td> 
              <td><%= order.address %></td> 
            <td><% order.order_items.each do |item| %>
              <%= item.quantity %>x
              <%= item.product.name %>
              <br/>
            <% end %></td>
            <td><%= link_to "Show", order, class:"btn btn-info" %></td>

            <% if order.confirmed == true %>
            <td><%= button_to "Done", order, method: :delete, confirm: "Are you sure?", class:"btn btn-danger"%></td>
            <%else%>
            <%= hidden_field :confirmed, :value=> true %>
            <td><%= button_to "Confirm", toggle_confirm_path(order), :remote => true, class:"btn btn-info" %></td>
            <%end%>
            </tr>
          </div>
        <% end %>
      </div>
    </tbody>
  </table>
</div>
<!-- Jika bukan admin -->
<% else %>
Access Denied
<%end%>

app/views/orders/new.html.erb
<div class="container">

<%= form_for(@order) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true, value: current_user.username %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email, value: current_user.email %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/orders/show.html.erb
          <div class="container">
            <p>Name: <%= @order.name %></p>
            <p>Email: <%= @order.email %></p>
            <p>Line Items: </p>
            <ul>
                <% @order.order_items.each do |item| %>
                    <li><%= item.quantity %> x <%= item.product.name %></li>
                <% end %>
            </ul>
            <% if current_user.try(:admin?) %>
                <%= link_to "Back to list", orders_path, class:"btn btn-dark" %>
            <% end %>
          </div>