config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  resources :orders

  # resources :line_items
  # resource :carts, only:[:show]
  resources :brands
  resources :types
  devise_for :users
  resources :products
  get 'home/index'
  get 'home/faq'
  get 'home/help'
  get 'home/about'
  get 'home/dashboard'
  root 'home#index'

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  post 'orders/:id/confirm' => "orders#toggle_confirm", as: "toggle_confirm"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # belongs_to :user, optional: true

  # LOGIC
  def sub_total
      sum = 0
      self.line_items.each do |line_item|
          sum+= line_item.total_price
      end
      return sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="row">
  <% @cart.line_items.each do |line_item| %>
  <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
    <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
      <% if line_item.product.image_product.attached?%>
        <img src="<%= (url_for(line_item.product.image_product))%>" class="w-100" width="300" height="300" alt="">
      <%else%>
        <%= image_tag "logo.png", class:"w-100" %>
      <%end%>
      <a href="#!"><div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div></a>                    
    </div>
  </div>
  <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
    <p><strong><%= line_item.product.name %></strong></p>
    <p>Harga: <%= number_to_currency(line_item.product.price, unit:'IDR ') %></p>
    <p>Kuantitas: <%= line_item.quantity %></p>
    <%= button_to "Remove item", line_item_path(line_item), method: :delete, class:"btn btn-danger btn-sm me-1 mb-2" %>
  </div>
  <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
    <div class="d-flex mb-4" style="max-width: 200px">
    <%= button_to "-", line_item_reduce_path(:id => line_item), method: :post, class:"btn btn-primary px-3 me-2" %>
    <span class="text-muted px-2">|</span>
    <p><%= line_item.quantity %></p>
    <span class="text-muted px-2">|</span>
    <%= button_to "+", line_item_add_path(:id => line_item), method: :post, class:"btn btn-primary px-3 me-2" %>
    </div>
    <p class="text-start text-md-center"><strong>Total: <%= number_to_currency(line_item.total_price, unit:'IDR ') %></strong></p>
  </div>
  <% end %>
</div>

app/views/carts/show.html.erb
<section class="vh-200" style="background-color: #508bfc;">
  <section class="h-100 gradient-custom">
    <div class="container py-5">
      <div class="row d-flex justify-content-center my-4">
        <div class="col-md-8">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Keranjang</h5>
            </div>
            <!-- ISI PRODUK -->
            <div class="card-body">
              <%= render "cart" %>
            </div>
          </div>
          <div class="mb-0">    
          </div>
        </div>
      
            <!-- Tabel -->
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Total</h5>
            </div>
            <div class="card-body">
              <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                 Produk
                 <span><%= number_to_currency(@cart.sub_total, unit:'IDR ') %></span>
               </li>
                <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                  Pengiriman
                  <span>Gratis</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                  <div>
                    <strong>Total Pembayaran</strong>
                  </div>
                  <span><strong><%= number_to_currency(@cart.sub_total, unit:'IDR ') %></strong></span>
                </li>
              </ul>
              <%= link_to "Bayar", new_order_path, class:"btn btn-primary btn-lg btn-block" %>
            </div>
          </div>
          <li class="text-start text-md-center">
            <span><%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger btn-sm me-1 mb-2" %></span>
          </li>
        </div>
      </div>
    </div>
  </section>
</section>