config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  resources :orders

  # resources :line_items
  # resource :carts, only:[:show]
  resources :brands
  resources :types
  devise_for :users
  resources :products
  get 'home/index'
  get 'home/faq'
  get 'home/help'
  get 'home/about'
  get 'home/dashboard'
  root 'home#index'

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  post 'orders/:id/confirm' => "orders#toggle_confirm", as: "toggle_confirm"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
    validates :byBrand, presence: true, uniqueness: true
    has_many :products
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # belongs_to :user, optional: true

  # LOGIC
  def sub_total
      sum = 0
      self.line_items.each do |line_item|
          sum+= line_item.total_price
      end
      return sum
  end
end

app/models/home.rb
class Home < ApplicationRecord
    has_one_attached :image_product
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
    belongs_to :order, optional: true
  
    # LOGIC
    def total_price
      self.quantity * self.product.price
    end
end

app/models/order.rb
class Order < ApplicationRecord
  # belongs_to :user
  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart, optional: true
    belongs_to :order

    # LOGIC
    def total_price
        self.quantity * self.product.price
    end
end

app/models/product.rb
class Product < ApplicationRecord
    def self.filter_search(name_search,type_select,brand_select)
        if name_search
            if name_search !="" && type_select == "" && brand_select == ""
                where("name LIKE?","%#{name_search}%")
            elsif name_search == "" && type_select != "" && brand_select == ""
                where('type_id = ?', type_select)
            elsif name_search == "" && type_select == "" && brand_select != ""
                where('brand_id = ?', brand_select)
            elsif name_search != "" && type_select != "" && brand_select == ""
                where("name LIKE? AND type_id = ?","%#{name_search}%", type_select)
            elsif name_search != "" && type_select == "" && brand_select != ""
                where("name LIKE? AND brand_id = ?","%#{name_search}%", brand_select)
            elsif name_search == "" && type_select != "" && brand_select != ""
                where("type_id LIKE? AND brand_id = ?",type_select, brand_select)
            elsif name_search != "" && type_select != "" && brand_select != ""
                where("name LIKE? AND type_id = ? AND brand_id = ?","%#{name_search}%", type_select, brand_select)
            else
                all
            end
        else
            all
        end
    end

    has_one_attached :image_product
    has_many :line_items, dependent: :destroy

    belongs_to :type
    belongs_to :brand
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # has_one :cart

  attr_writer :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login]


  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  validates :username, presence: true, uniqueness: { case_sensitive: false }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @cart = @current_cart
    
  end
 
  def about
  end
  def dashboard
    @products = Product.filter_search(params[:name_search], params[:type_select], params[:brand_select])
  end

  # def cart
  #   quantity = params[:quantity].to_i
  #   product_id = params[:product]
  #   @product = Product.find(product_id)
  #   @cart.add(@product, @product.price_product, quantity)
  #   redirect_to  request.referer || "/"
  #   flash[:notice] = "#{@product.name} has been added to the Cart."
  # end

  # def create_order
  #   total_price_delivery = 0
  #   total_price_items = @cart.total_items
  #   total_all_price = total_price_delivery + total_price_items
  
  #   @order = Order.new
  #   @order.number = "#{current_user.id}-#{Time.now.to_i}"
  #   @order.user_id = current_user.id
  #   @order.total_price_items = total_price_items
  #   @order.total_price_delivery = total_price_delivery
  #   @order.total_all_price = total_all_price
  #   @order.save
  #   @cart.update(:order_id => @order.id)
  #   redirect_to root_path
  #   flash[:notice] = "Your Order has been created"
  # end
  




  def cover_url 
    rails_blob_path(self.image_product, disposition: "attachment", only_path: true)
  end

  def persisted?
    false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    # def data_currency(data)
    #   number_to_currency(data, unit: 'Rp. ', :precision => 0)
    # end

    # def current_cart
    #   if !session[:cart_id].nil?
    #       Cart.find(session[:cart_id])
    #   else
    #       Cart.new
    #   end
    # end



    # private
    # def current_cart
    #   if session[:cart_id]
    #     cart = Cart.find_by(:id => session[:cart_id])
    #     if cart.present?
    #       @current_cart = cart
    #     else
    #       session[:cart_id] = nil
    #     end
    #   end

    #   if session[:cart_id] == nil
    #     @current_cart = Cart.create
    #     session[:cart_id] = @current_cart.id
    #   end
    # end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_footer.html.erb
    <br/>
    <br/>
    <br/>
    <br/>


<!-- Products End -->
        <!-- Bootstrap about lite -->
      <div class="container-fluid"style="background-color: #e3f2fd;" >
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="mb-4= display-5 font-weight-semi-bold"><span class="text-dark font-weight-bold  px-3 mr-1">TKB</span>Gadget</h1>
                </a>
                <p>Toko yang menjual keperluan Gadget.</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-success mr-3"></i>Politeknik Elektronika Negeri Surabaya</p>
                <p class="mb-2"><i class="fa fa-envelope text-success mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-success mr-3"></i>085745536597</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Pintasan</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Beranda</a>
                            <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>katalog kami</a>
                            <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>katalog Detail</a>
                            <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Keranjang</a>
                            <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Tentang Kami</a>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">TKB Gadget</a>. 2022 All Rights Reserved. Designed
                    by
                    <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a><br>
                    Powered By <a href="https://www.instagram.com/mtasshiddiqy" target="_blank">M Thoyyib Asshiddiqy</a>
                </p>
            </div>

app/views/layouts/_header.html.erb

<nav class="navbar sticky-top navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <%= image_tag "logo.png", width:"30", height:"24", class:"d-inline-block align-text-top"%>
    <%= link_to "TKB GADGET STORE", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <div class="d-inline-flex align-items-center">
            <%= link_to "FAQs", home_faq_path, class:"nav-link active"%>
            <span class="text-muted px-2">|</span>
            <%= link_to "Bantuan", home_help_path, class:"nav-link active"%>
            <span class="text-muted px-2">|</span>
            <%= link_to "About", home_about_path, class:"nav-link active"%>
            <span class="text-muted px-2">|</span>
            <%= link_to "Produk", products_path, class:"nav-link active"%>
            <span class="text-muted px-2">|</span>
            <%= link_to "Keranjang", cart_path(@current_cart), class:"nav-link active"%>
          </div>
      </ul>
      <div class="col-lg-6 text-center text-lg-right">
        <div class="d-inline-flex align-items-center">
          <a class="text-light px-2" href=""><i class="fab fa-twitter"></i></a>
          <a class="text-light px-2" href=""><i class="fab fa-facebook-f"></i></a>
          <a class="text-light px-2" href=""><i class="fab fa-instagram"></i></a>
          <a class="text-light pl-2" href=""><i class="fab fa-youtube"></i></a>
        </div>
      </div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if current_user.try(:admin?) %>
        <%= link_to "Admin", home_dashboard_path, class:"nav-link active"%>
        <span class="text-muted px-2">|</span>
      <%end%>
      <% if user_signed_in?%>
        <%= button_to "Halo #{current_user.username}", edit_user_registration_path, method: :get, class:"btn btn-outline-light"%>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-outline-light" %>
      <% else %>
        <%= button_to "Sign Up", new_user_registration_path, method: :get, class:"btn btn-outline-light"%>
        <%= button_to "Sign In", new_user_session_path, method: :get, class:"btn btn-outline-light"%>
      <%end%>
      </ul>
    </div>  
  </div>
</nav>




app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <title>TKB Gadget Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= render "layouts/header"%>
    <div class="container sticky-top">
      <% if notice%>
        <%= render "layouts/alerts" %>
      <%end %>
    </div>
    <%= yield %>


    <%= render "layouts/footer"%>

  </body>
</html>